apiVersion: v1
kind: Service
metadata:
  name: partitioning-controller
  labels:
    app: partitioning-controller
spec:
  type: ClusterIP
  selector:
    app: partitioning-controller
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: partitioning-controller
  namespace: default  
  labels:
    app: partitioning-controller
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: partitioning-controller
  template:
    metadata:
      labels:
        app: partitioning-controller
    spec:
      containers:
        - name: partitioning-controller
          image: sebastiansteininger/noredb-partitioning-controller:dev
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          envFrom:
            - configMapRef:
                name: veritas-config
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_NAME
              value: "partitioning-controller"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: partitioning-controller-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: partitioning-controller
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30
      selectPolicy: Max