apiVersion: v1
kind: ConfigMap
metadata:
  name: veritas-config
data:
  # Use the StatefulSet pod DNS names so each pod can reach the others.
  # Format: <pod-name>.<headless-service>.<namespace>.svc.cluster.local
  # For the StatefulSet named "veritas", headless service "veritas-headless",
  # in the "default" namespace, the three pod names are:
  # veritas-0.veritas-headless.default.svc.cluster.local
  # veritas-1.veritas-headless.default.svc.cluster.local
  # veritas-2.veritas-headless.default.svc.cluster.local
  #
  # If you deploy to a different namespace, update the suffix accordingly.
  VERITAS_NODES: "veritas-0.veritas-headless.default.svc.cluster.local,veritas-1.veritas-headless.default.svc.cluster.local,veritas-2.veritas-headless.default.svc.cluster.local,veritas-3.veritas-headless.default.svc.cluster.local,veritas-4.veritas-headless.default.svc.cluster.local"
  # DNS TTL in seconds (app default is 5)
  VERITAS_DNS_TTL: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: veritas-headless
  labels:
    app: veritas
spec:
  clusterIP: None
  selector:
    app: veritas
  ports:
    - name: http
      port: 80
      targetPort: 80
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: veritas
  namespace: default
  labels:
    app: veritas
spec:
  serviceName: veritas-headless
  replicas: 5
  selector:
    matchLabels:
      app: veritas
  template:
    metadata:
      labels:
        app: veritas
    spec:
      # Enable anti-affinity to spread pods across nodes - optional but recommended
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: veritas
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: veritas
          image: sebastiansteininger/veritas:alpha
          ports:
            - name: http
              hostPort: 80
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: veritas-config
          env:
            - name: ORDINAL_NUMBER
              valueFrom:
              fieldRef:
                fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            - name: LOG_LEVEL
              value: "TRACE"
          volumeMounts:
            - name: app-data
              mountPath: /data
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /tick
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /tick
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always # For development, always pull the latest image
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  volumeClaimTemplates:
    - metadata:
        name: app-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi