apiVersion: v1
kind: ConfigMap
metadata:
  name: noredb-config
data:
  # Reference the Veritas StatefulSet pod DNS names for service discovery.
  # NoReDB uses Veritas for distributed coordination and service registration.
  # Format: <pod-name>.<headless-service>.<namespace>.svc.cluster.local
  VERITAS_NODES: "veritas-0.veritas-headless.default.svc.cluster.local,veritas-1.veritas-headless.default.svc.cluster.local,veritas-2.veritas-headless.default.svc.cluster.local,veritas-3.veritas-headless.default.svc.cluster.local,veritas-4.veritas-headless.default.svc.cluster.local"
  # DNS TTL in seconds (app default is 5)
  VERITAS_DNS_TTL: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: noredb-service
  labels:
    app: noredb
spec:
  type: ClusterIP
  selector:
    app: noredb
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: noredb
  namespace: default
  labels:
    app: noredb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: noredb
  template:
    metadata:
      labels:
        app: noredb
    spec:
      # Enable anti-affinity to spread pods across nodes - optional but recommended
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: noredb
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: noredb
          image: sebastiansteininger/noredb-canvasdb:alpha
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          envFrom:
            - configMapRef:
                name: noredb-config
          env:
            - name: LOG_LEVEL
              value: "TRACE"
          volumeMounts:
            - name: app-data
              mountPath: /data
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always # For development, always pull the latest image
      volumes:
        - name: app-data
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1