// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: noredb.proto

package noredb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`        // The index of the transaction log
	Key           uint32                 `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`            // The key for the data entry
	Timestamp     []byte                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // The timestamp of the data entry
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`         // The value of the data entry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_noredb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_noredb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_noredb_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Data) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Data) GetTimestamp() []byte {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Data) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // The index of the transaction
	Key           uint32                 `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`     // The key for the data entry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_noredb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noredb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_noredb_proto_rawDescGZIP(), []int{1}
}

func (x *DataRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DataRequest) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`        // The index of the transaction
	Key           uint32                 `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`            // The key for the data entry
	Timestamp     []byte                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // The timestamp of the data entry
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`         // The value of the data entry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_noredb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noredb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_noredb_proto_rawDescGZIP(), []int{2}
}

func (x *DataResponse) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DataResponse) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *DataResponse) GetTimestamp() []byte {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DataResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Commit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // The index of the transaction
	// 0b0000 = pending,
	// 0b0001 = success,
	// 0b0010 = failure,
	// 0b0011 = unknown,
	// 0b0100 = aborted,
	// 0b0110 = rolled back
	Status        int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_noredb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_noredb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_noredb_proto_rawDescGZIP(), []int{3}
}

func (x *Commit) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Commit) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // The index of the transaction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_noredb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noredb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_noredb_proto_rawDescGZIP(), []int{4}
}

func (x *StreamRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_noredb_proto protoreflect.FileDescriptor

const file_noredb_proto_rawDesc = "" +
	"\n" +
	"\fnoredb.proto\x12\x06noredb\"b\n" +
	"\x04Data\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x10\n" +
	"\x03key\x18\x02 \x01(\rR\x03key\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\fR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"5\n" +
	"\vDataRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x10\n" +
	"\x03key\x18\x02 \x01(\rR\x03key\"j\n" +
	"\fDataResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x10\n" +
	"\x03key\x18\x02 \x01(\rR\x03key\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\fR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"6\n" +
	"\x06Commit\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"%\n" +
	"\rStreamRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index2\xa0\x01\n" +
	"\bDatabase\x12%\n" +
	"\x03Set\x12\f.noredb.Data\x1a\x0e.noredb.Commit\"\x00\x122\n" +
	"\x03Get\x12\x13.noredb.DataRequest\x1a\x14.noredb.DataResponse\"\x00\x129\n" +
	"\x06GetAll\x12\x15.noredb.StreamRequest\x1a\x14.noredb.DataResponse\"\x000\x01B>Z<github.com/SteiningerSebastian/webcanvas/grpc-general;noredbb\x06proto3"

var (
	file_noredb_proto_rawDescOnce sync.Once
	file_noredb_proto_rawDescData []byte
)

func file_noredb_proto_rawDescGZIP() []byte {
	file_noredb_proto_rawDescOnce.Do(func() {
		file_noredb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_noredb_proto_rawDesc), len(file_noredb_proto_rawDesc)))
	})
	return file_noredb_proto_rawDescData
}

var file_noredb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_noredb_proto_goTypes = []any{
	(*Data)(nil),          // 0: noredb.Data
	(*DataRequest)(nil),   // 1: noredb.DataRequest
	(*DataResponse)(nil),  // 2: noredb.DataResponse
	(*Commit)(nil),        // 3: noredb.Commit
	(*StreamRequest)(nil), // 4: noredb.StreamRequest
}
var file_noredb_proto_depIdxs = []int32{
	0, // 0: noredb.Database.Set:input_type -> noredb.Data
	1, // 1: noredb.Database.Get:input_type -> noredb.DataRequest
	4, // 2: noredb.Database.GetAll:input_type -> noredb.StreamRequest
	3, // 3: noredb.Database.Set:output_type -> noredb.Commit
	2, // 4: noredb.Database.Get:output_type -> noredb.DataResponse
	2, // 5: noredb.Database.GetAll:output_type -> noredb.DataResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_noredb_proto_init() }
func file_noredb_proto_init() {
	if File_noredb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_noredb_proto_rawDesc), len(file_noredb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noredb_proto_goTypes,
		DependencyIndexes: file_noredb_proto_depIdxs,
		MessageInfos:      file_noredb_proto_msgTypes,
	}.Build()
	File_noredb_proto = out.File
	file_noredb_proto_goTypes = nil
	file_noredb_proto_depIdxs = nil
}
