apiVersion: v1
kind: Service
metadata:
  name: noredb-headless
  labels:
    app: noredb
spec:
  clusterIP: None
  selector:
    app: noredb
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: noredb
  namespace: default
  labels:
    app: noredb
spec:
  serviceName: noredb-headless
  replicas: 9
  selector:
    matchLabels:
      app: noredb
  template:
    metadata:
      labels:
        app: noredb
    spec:
      # Enable anti-affinity to spread pods across nodes - optional but recommended
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: noredb
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: noredb
          image: sebastiansteininger/noredb-canvasdb:alpha
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
          envFrom:
            - configMapRef:
                name: veritas-config
          env:
            - name: LOG_LEVEL
              value: "TRACE"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_NAME
              value: "noredb-headless"
          volumeMounts:
            - name: app-data
              mountPath: /data
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always # For development, always pull the latest image
  volumeClaimTemplates:
    - metadata:
        name: app-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1