apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcanvas
  namespace: default
  labels:
    app: webcanvas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webcanvas
  template:
    metadata:
      labels:
        app: webcanvas
    spec:
      containers:
      - name: webcanvas
        image: webcanvas:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: VERITAS_NODES
          valueFrom:
            configMapKeyRef:
              name: veritas-config
              key: VERITAS_NODES
        - name: Logging__LogLevel__Default
          value: "Information"
        - name: ServiceRegistration__ServiceKey
          value: "WebCanvas"
        - name: ServiceRegistration__RegistrationIntervalSeconds
          value: "30"
        - name: ServiceRegistration__Port
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: webcanvas
  namespace: default
  labels:
    app: webcanvas
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: webcanvas
---
apiVersion: v1
kind: Service
metadata:
  name: webcanvas-headless
  namespace: default
  labels:
    app: webcanvas
spec:
  clusterIP: None  # Headless service for peer-to-peer communication
  selector:
    app: webcanvas
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  publishNotReadyAddresses: true  # Allow DNS for pods not yet ready
---
apiVersion: v1
kind: Service
metadata:
  name: webcanvas-loadbalancer
  namespace: default
  labels:
    app: webcanvas
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: webcanvas

